version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 5173:5173  
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      platforms:
        - "linux/arm64" 
        # - "linux/amd64"
    environment:
      PORT: 5000
      FRONTEND_URL: 'http://localhost:5173'
      JWT_SECRET: ${JWT_SECRET}
      MYSQL_URL_DOCKER: ${MYSQL_URL_DOCKER}
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge